-- Diagnóstico do banco Sankhya (SQL Server) para o Sistema Vendas x Metas.
-- SOMENTE LEITURA: consulta o catálogo do banco, não altera nada.
-- Resultado: uma linha por campo, com STATUS = OK, CAMPO NAO ENCONTRADO ou TABELA NAO ENCONTRADA.
-- Exporte o resultado para Excel e envie. "Não encontrado" pode ser só outro nome de campo
-- na sua versão; a consulta 3 (campos_adicionais.sql) ajuda a achar o equivalente.

SELECT N.BLOCO, N.TABELA, N.CAMPO, N.USO,
       CASE
         WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS C WHERE C.TABLE_NAME = N.TABELA AND C.COLUMN_NAME = N.CAMPO) THEN 'OK'
         WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_NAME = N.TABELA) THEN 'CAMPO NAO ENCONTRADO'
         ELSE 'TABELA NAO ENCONTRADA'
       END AS STATUS
FROM (VALUES
  ('1 Vendas (ja usado)', 'TGFCAB', 'NUNOTA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'NUMNOTA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'CODEMP', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'DTNEG', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'DTMOV', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'DTFATUR', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'CODTIPOPER', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'DHTIPOPER', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'TIPMOV', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'STATUSNOTA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'CODPARC', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'CODVEND', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'CODTIPVENDA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'VLRNOTA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'VLRFRETE', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'PENDENTE', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'DTENTSAI', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFCAB', 'ORDEMCARGA', 'cabecalho da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'NUNOTA', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'SEQUENCIA', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'CODPROD', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'QTDNEG', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'QTDENTREGUE', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRUNIT', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRTOT', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRDESC', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRICMS', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRIPI', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'VLRSUBST', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'CUSTO', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'CODVOL', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'CONTROLE', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'CODVEND', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFITE', 'PENDENTE', 'itens da nota / pedido'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'CODTIPOPER', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'DHALTER', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'DESCROPER', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'TIPMOV', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'ATUALEST', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFTOP', 'ATUALFIN', 'tipos de operacao'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'CODPROD', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'DESCRPROD', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'CODGRUPOPROD', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'PESOLIQ', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'PESOBRUTO', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'CODVOL', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'ATIVO', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFPRO', 'MARCA', 'produtos'),
  ('1 Vendas (ja usado)', 'TGFGRU', 'CODGRUPOPROD', 'grupos de produto'),
  ('1 Vendas (ja usado)', 'TGFGRU', 'DESCRGRUPOPROD', 'grupos de produto'),
  ('1 Vendas (ja usado)', 'TGFGRU', 'CODGRUPAI', 'grupos de produto'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CODPARC', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'NOMEPARC', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'RAZAOSOCIAL', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CGC_CPF', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CODCID', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CODREG', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CODVEND', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'LIMCRED', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'DTCAD', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'ATIVO', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'CLIENTE', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TGFPAR', 'BLOQUEAR', 'clientes / parceiros'),
  ('1 Vendas (ja usado)', 'TSICID', 'CODCID', 'cidades'),
  ('1 Vendas (ja usado)', 'TSICID', 'NOMECID', 'cidades'),
  ('1 Vendas (ja usado)', 'TSICID', 'UF', 'cidades'),
  ('1 Vendas (ja usado)', 'TSIUFS', 'CODUF', 'estados'),
  ('1 Vendas (ja usado)', 'TSIUFS', 'UF', 'estados'),
  ('1 Vendas (ja usado)', 'TSIUFS', 'DESCRICAO', 'estados'),
  ('1 Vendas (ja usado)', 'TSIREG', 'CODREG', 'regioes (hierarquia)'),
  ('1 Vendas (ja usado)', 'TSIREG', 'NOMEREG', 'regioes (hierarquia)'),
  ('1 Vendas (ja usado)', 'TSIREG', 'CODREGPAI', 'regioes (hierarquia)'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'CODVEND', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'APELIDO', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'TIPVEND', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'CODGER', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'CODREG', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TGFVEN', 'ATIVO', 'vendedores / supervisores / gerentes'),
  ('1 Vendas (ja usado)', 'TSIEMP', 'CODEMP', 'empresas'),
  ('1 Vendas (ja usado)', 'TSIEMP', 'NOMEFANTASIA', 'empresas'),
  ('2 Metas', 'TGFMET', 'CODMETA', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'DTREF', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'CODVEND', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'CODPROD', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'CODGRUPOPROD', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'CODPARC', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'QTDPREV', 'metas (confirmar campos)'),
  ('2 Metas', 'TGFMET', 'VLRPREV', 'metas (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'CODPROD', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'CODEMP', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'DTATUAL', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'CUSREP', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'CUSMED', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFCUS', 'CUSGER', 'custo do produto (confirmar campos)'),
  ('3 Margem', 'TGFDIN', 'NUNOTA', 'impostos por item'),
  ('3 Margem', 'TGFDIN', 'SEQUENCIA', 'impostos por item'),
  ('3 Margem', 'TGFDIN', 'CODIMP', 'impostos por item'),
  ('3 Margem', 'TGFDIN', 'BASE', 'impostos por item'),
  ('3 Margem', 'TGFDIN', 'VALOR', 'impostos por item'),
  ('4 Financeiro', 'TGFFIN', 'NUFIN', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'NUNOTA', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'CODEMP', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'CODPARC', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'CODVEND', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'RECDESP', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'DTNEG', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'DTVENC', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'DHBAIXA', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'VLRDESDOB', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'VLRBAIXA', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'CODTIPTIT', 'titulos a receber'),
  ('4 Financeiro', 'TGFFIN', 'PROVISAO', 'titulos a receber'),
  ('4 Financeiro', 'TGFTPV', 'CODTIPVENDA', 'condicao de pagamento'),
  ('4 Financeiro', 'TGFTPV', 'DHALTER', 'condicao de pagamento'),
  ('4 Financeiro', 'TGFTPV', 'DESCRTIPVENDA', 'condicao de pagamento'),
  ('5 Estoque', 'TGFEST', 'CODEMP', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'CODPROD', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'CODLOCAL', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'CONTROLE', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'ESTOQUE', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'RESERVADO', 'estoque, lote e validade'),
  ('5 Estoque', 'TGFEST', 'DTVAL', 'estoque, lote e validade'),
  ('6 Pedidos e atendimento', 'TGFVAR', 'NUNOTA', 'vinculo pedido -> nota (cortes)'),
  ('6 Pedidos e atendimento', 'TGFVAR', 'SEQUENCIA', 'vinculo pedido -> nota (cortes)'),
  ('6 Pedidos e atendimento', 'TGFVAR', 'NUNOTAORIG', 'vinculo pedido -> nota (cortes)'),
  ('6 Pedidos e atendimento', 'TGFVAR', 'SEQUENCIAORIG', 'vinculo pedido -> nota (cortes)'),
  ('6 Pedidos e atendimento', 'TGFVAR', 'QTDATENDIDA', 'vinculo pedido -> nota (cortes)'),
  ('6 Pedidos e atendimento', 'TGFORD', 'ORDEMCARGA', 'ordens de carga / rotas'),
  ('6 Pedidos e atendimento', 'TGFORD', 'CODEMP', 'ordens de carga / rotas'),
  ('6 Pedidos e atendimento', 'TGFORD', 'DTINIC', 'ordens de carga / rotas'),
  ('6 Pedidos e atendimento', 'TGFORD', 'CODVEICULO', 'ordens de carga / rotas'),
  ('7 Preco', 'TGFTAB', 'NUTAB', 'tabelas de preco'),
  ('7 Preco', 'TGFTAB', 'CODTAB', 'tabelas de preco'),
  ('7 Preco', 'TGFTAB', 'DTVIGOR', 'tabelas de preco'),
  ('7 Preco', 'TGFEXC', 'NUTAB', 'preco por produto na tabela'),
  ('7 Preco', 'TGFEXC', 'CODPROD', 'preco por produto na tabela'),
  ('7 Preco', 'TGFEXC', 'VLRVENDA', 'preco por produto na tabela'),
  ('8 Dicionario', 'TDDTAB', 'NOMETAB', 'dicionario de tabelas do Sankhya'),
  ('8 Dicionario', 'TDDTAB', 'DESCRTAB', 'dicionario de tabelas do Sankhya'),
  ('8 Dicionario', 'TDDCAM', 'NOMETAB', 'dicionario de campos (acha os AD_)'),
  ('8 Dicionario', 'TDDCAM', 'NOMECAMPO', 'dicionario de campos (acha os AD_)'),
  ('8 Dicionario', 'TDDCAM', 'DESCRCAMPO', 'dicionario de campos (acha os AD_)'),
  ('8 Dicionario', 'TDDCAM', 'TIPCAMPO', 'dicionario de campos (acha os AD_)')
) AS N (BLOCO, TABELA, CAMPO, USO)
ORDER BY N.BLOCO, N.TABELA, N.CAMPO
