-- Volume e histórico disponível (Oracle e SQL Server). Rode depois do diagnóstico; se alguma tabela
-- não existir, apague a linha dela. SOMENTE LEITURA.
SELECT 'TGFCAB vendas/devolucoes' TABELA, COUNT(*) LINHAS, MIN(DTNEG) DE, MAX(DTNEG) ATE FROM TGFCAB WHERE TIPMOV IN ('V','D')
UNION ALL SELECT 'TGFCAB pedidos', COUNT(*), MIN(DTNEG), MAX(DTNEG) FROM TGFCAB WHERE TIPMOV = 'P'
UNION ALL SELECT 'TGFITE', COUNT(*), NULL, NULL FROM TGFITE
UNION ALL SELECT 'TGFFIN a receber', COUNT(*), MIN(DTVENC), MAX(DTVENC) FROM TGFFIN WHERE RECDESP = 1
UNION ALL SELECT 'TGFMET', COUNT(*), MIN(DTREF), MAX(DTREF) FROM TGFMET
UNION ALL SELECT 'TGFEST', COUNT(*), NULL, NULL FROM TGFEST
UNION ALL SELECT 'TGFPAR', COUNT(*), MIN(DTCAD), MAX(DTCAD) FROM TGFPAR
UNION ALL SELECT 'TGFPRO', COUNT(*), NULL, NULL FROM TGFPRO
UNION ALL SELECT 'TGFVEN', COUNT(*), NULL, NULL FROM TGFVEN
