-- Campos adicionais (AD_) e tabelas personalizadas do Sankhya. Funciona em Oracle e SQL Server.
-- SOMENTE LEITURA. Serve para achar onde estão Linha, Família, Mix Comercial, Mix Bíblia, Rede,
-- Perfil, Região do país, supervisor, motivo de devolução etc. Exporte o resultado para Excel.

SELECT C.NOMETAB AS TABELA, C.NOMECAMPO AS CAMPO, C.DESCRCAMPO AS DESCRICAO, C.TIPCAMPO AS TIPO
FROM TDDCAM C
WHERE C.NOMETAB IN ('TGFCAB', 'TGFCUS', 'TGFDIN', 'TGFEST', 'TGFEXC', 'TGFFIN', 'TGFGRU', 'TGFITE', 'TGFMET', 'TGFORD', 'TGFPAR', 'TGFPRO', 'TGFTAB', 'TGFTOP', 'TGFTPV', 'TGFVAR', 'TGFVEN', 'TSICID', 'TSIEMP', 'TSIREG', 'TSIUFS')
  AND (C.NOMECAMPO LIKE 'AD!_%' ESCAPE '!'
       OR UPPER(C.DESCRCAMPO) LIKE '%MIX%' OR UPPER(C.DESCRCAMPO) LIKE '%REDE%'
       OR UPPER(C.DESCRCAMPO) LIKE '%LINHA%' OR UPPER(C.DESCRCAMPO) LIKE '%FAMIL%'
       OR UPPER(C.DESCRCAMPO) LIKE '%PERFIL%' OR UPPER(C.DESCRCAMPO) LIKE '%SUPERV%'
       OR UPPER(C.DESCRCAMPO) LIKE '%MOTIVO%' OR UPPER(C.DESCRCAMPO) LIKE '%CUSTO%'
       OR UPPER(C.DESCRCAMPO) LIKE '%COMISS%' OR UPPER(C.DESCRCAMPO) LIKE '%BONIF%')
ORDER BY C.NOMETAB, C.NOMECAMPO;

-- Tabelas personalizadas (AD_), por exemplo cadastro de redes ou de mix:
SELECT T.NOMETAB AS TABELA, T.DESCRTAB AS DESCRICAO
FROM TDDTAB T
WHERE T.NOMETAB LIKE 'AD!_%' ESCAPE '!'
ORDER BY T.NOMETAB;
